version: '3.7'

networks:
  dbnetwork:

services:
  db:
    image: postgres
    container_name: db
    restart: always
    network_mode: host
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rinhabackend
    volumes:
      - ./scripts/ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
    expose:
      - "5432"
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "1.5GB"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 15s
      timeout: 25s

  application1:
    image: patrickchagas/rinha-backend-api:1.4
    container_name: application1
    restart: always
    network_mode: host
    depends_on:
      db:
        condition: service_healthy
    environment:
      - env=production
      - PORT=:8000
      - DATABASE_URL=postgres://postgres:postgres@localhost:5432/rinhabackend?sslmode=disable&pool_min_conns=0&pool_max_conns=100
    expose:
      - "8000"
    ports:
      - "8000:8000"
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: "0.5GB"
  
  application2:
    image: patrickchagas/rinha-backend-api:1.4
    container_name: application2
    restart: always
    network_mode: host
    depends_on:
      db:
        condition: service_healthy
    environment:
      - env=production
      - PORT=:8001
      - DATABASE_URL=postgres://postgres:postgres@localhost:5432/rinhabackend?sslmode=disable&pool_min_conns=0&pool_max_conns=100
    expose:
      - "8001"
    ports:
      - "8001:8001"
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: "0.5GB"
  
  nginx:
    image: nginx
    container_name: nginx
    hostname: api
    network_mode: host
    # networks:
    #   - dbnetwork
    volumes:
      - ./scripts/nginx/:/etc/nginx/
    depends_on:
      - application1
      - application2
    ulimits:
      nproc: 1000000
      nofile:
        soft: 1000000
        hard: 1000000
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "0.5GB"

